% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
  12pt,
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage{setspace}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Chapter 3: Environmental and Social Determinants of Cognitive Health in Puente Piedra, Peru},
  pdfauthor={Gabrielle Benoit},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Chapter 3: Environmental and Social Determinants of Cognitive
Health in Puente Piedra, Peru}
\author{Gabrielle Benoit}
\date{2026-04-10}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{3}
\tableofcontents
}
\setstretch{2}
\subsection{Download Historical Purple Air Data via Data Download
Tool}\label{download-historical-purple-air-data-via-data-download-tool}

Sensor history:
\url{https://api.purpleair.com/\#api-sensors-get-sensor-history}

Fields:
pm10.0\_atm\_a,pm10.0\_atm\_b,pm10.0\_atm,voc\_a,voc\_b,voc,humidity,humidity\_a,humidity\_b,
temperature,temperature\_a,temperature\_b,pm2.5\_atm\_a,pm2.5\_atm\_b,pm2.5\_atm

Date range: 22-01-01 to 26-01-10

1-month average

\begin{center}\includegraphics{PurpleAir_SocioDem_files/figure-latex/purpleair_clean_pipeline-1} \end{center}

\begin{center}\includegraphics{PurpleAir_SocioDem_files/figure-latex/purpleair_clean_pipeline-2} \end{center}

\begin{center}\includegraphics{PurpleAir_SocioDem_files/figure-latex/purpleair_clean_pipeline-3} \end{center}

\subsection{Visualizations: Processed Exposure Time
Series}\label{visualizations-processed-exposure-time-series}

\begin{center}\includegraphics{PurpleAir_SocioDem_files/figure-latex/unnamed-chunk-1-1} \end{center}

\begin{center}\includegraphics{PurpleAir_SocioDem_files/figure-latex/unnamed-chunk-1-2} \end{center}

\begin{verbatim}
## # A tibble: 4 x 9
##   variable             n  mean    sd median   p25   p75   min   max
##   <chr>            <int> <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl>
## 1 Humidity (%)         6  54.8 1.46    54.7  53.8  55.6  52.9  56.8
## 2 PM10 (µg/m³)         6  41.9 3.89    40.6  39.4  44.2  37.9  48.0
## 3 PM2.5 (µg/m³)        6  35.0 3.89    33.3  32.6  38.2  30.9  40.1
## 4 Temperature (°F)     6  77.2 0.889   77.7  76.7  77.7  75.7  77.8
\end{verbatim}

\subsection{Adding location of sensor}\label{adding-location-of-sensor}

Unable to get this via the data download tool, need to use the API
directly

\begin{verbatim}
## 
## FALSE 
##     6
\end{verbatim}

\begin{verbatim}
## # A tibble: 6 x 11
##   sensor_id mean_pm25 mean_pm10 mean_humidity mean_temperature abs_thresh
##   <fct>         <dbl>     <dbl>         <dbl>            <dbl>      <dbl>
## 1 159005         32.7      39.9          55.6             77.6          5
## 2 159435         30.9      41.3          52.9             77.7          5
## 3 159599         40.1      48.0          53.8             75.7          5
## 4 180021         39.6      45.2          53.9             77.7          5
## 5 180043         32.6      37.9          56.8             76.4          5
## 6 180119         34.0      39.2          55.6             77.8          5
## # i 5 more variables: rel_thresh <dbl>, sensor_id_clean <dbl>,
## #   sensor_name <chr>, latitude <dbl>, longitude <dbl>
\end{verbatim}

\begin{verbatim}
## Deleting source `/Users/gabriellebenoit/Documents/GitHub/peru_air/purpleair__all_sensors.gpkg' using driver `GPKG'
## Writing layer `purpleair__all_sensors' to data source 
##   `/Users/gabriellebenoit/Documents/GitHub/peru_air/purpleair__all_sensors.gpkg' using driver `GPKG'
## Writing 6 features with 2 fields and geometry type Point.
\end{verbatim}

\subsection{Socio-demographic Data}\label{socio-demographic-data}

New map, numbered by section.
\href{https://www.google.com/maps/d/edit?mid=1ZxIT6hY4dc9rtQl3oUCLNVQoDkfRK5w&usp=sharing}{Final
version of the map} includes sector 5.

Confirmed (as of March 25th, 2026) working dataset: ``Base de datos
(Monica)\_09.16.2024\_MN edits 09.19.2024 copy 3.xlsx''

\subsection{Primary variables of
interest}\label{primary-variables-of-interest}

Cognitive scores: - ACE - RUADS - PFAQ - Dementia - Dementia AM -
Dementia AJ - Dementia AJ ALT - deterioro cognitivo

Exposure-related: - pollution (pm2.5, pm10) - temperature - humidity

Geography: (account for clustering) - Distrito - Sector -
Conglomerado/pin

Core standard confounders: - age - sex - education - occupation

Health-related: - bmi - glucose\_lev - hypertension

Socioeconomic: - overcrowding - health\_insurance - civil\_stat

\subsection{Using the google map data}\label{using-the-google-map-data}

Only 4 unmatched out of 1,099 rows.. negligible. Will proceed with the
join. Those 4 participants simply won't have coordinates and will be
dropped from the spatial analysis.

Many-to-many warning -- makes sense, as it is expected that multiple
survey participants will live in the same conglomerate (same
pin/location point), so one KML point matches many survey rows. That's
expected for cluster-based sampling.

\begin{verbatim}
## Driver: KML 
## Available layers:
##   layer_name geometry_type features fields crs_name
## 1   Sector 3      3D Point      264      2   WGS 84
## 2   Sector 1      3D Point      198      2   WGS 84
## 3   Sector 4      3D Point      200      2   WGS 84
## 4   Sector 2      3D Point      185      2   WGS 84
## 5   Sector 5      3D Point      259      2   WGS 84
\end{verbatim}

\begin{verbatim}
## [1] 1106
\end{verbatim}

\begin{verbatim}
## [1] "Name"        "Description" "geometry"
\end{verbatim}

\begin{verbatim}
## Simple feature collection with 6 features and 2 fields
## Geometry type: POINT
## Dimension:     XYZ
## Bounding box:  xmin: -77.09736 ymin: -11.8496 xmax: -77.0945 ymax: -11.84723
## z_range:       zmin: 0 zmax: 0
## Geodetic CRS:  WGS 84
##   Name Description                       geometry
## 1  407             POINT Z (-77.09736 -11.8472...
## 2  409             POINT Z (-77.09628 -11.8477...
## 3  415             POINT Z (-77.09686 -11.8482 0)
## 4  417             POINT Z (-77.09519 -11.8496 0)
## 5  418             POINT Z (-77.09572 -11.8490...
## 6  420             POINT Z (-77.0945 -11.84954 0)
\end{verbatim}

\begin{verbatim}
## 
## FALSE  TRUE 
##     4  1095
\end{verbatim}

\begin{verbatim}
## 
## Sector 1 Sector 3 
##        1        3
\end{verbatim}

\begin{verbatim}
## [1] 1989
\end{verbatim}

\begin{verbatim}
## Deleting source `/Users/gabriellebenoit/Documents/GitHub/peru_air/spatial_survey_data.gpkg' using driver `GPKG'
## Writing layer `spatial_survey_data' to data source 
##   `/Users/gabriellebenoit/Documents/GitHub/peru_air/spatial_survey_data.gpkg' using driver `GPKG'
## Writing 1989 features with 25 fields and geometry type 3D Point.
\end{verbatim}

\subsection{Spatial Join for All
Variables}\label{spatial-join-for-all-variables}

\begin{verbatim}
## Simple feature collection with 6 features and 6 fields
## Geometry type: POINT
## Dimension:     XYZ
## Bounding box:  xmin: 271508.3 ymin: 8689420 xmax: 271626.9 ymax: 8689480
## z_range:       zmin: 0 zmax: 0
## Projected CRS: WGS 84 / UTM zone 18S
##   conglomerado_chr         nearest_sensor_name exposure_pm25 exposure_pm10
## 1              407 GEOHealth_MiPeru_Chavinillo      32.70588      39.94412
## 2              407 GEOHealth_MiPeru_Chavinillo      32.70588      39.94412
## 3              409 GEOHealth_MiPeru_Chavinillo      32.70588      39.94412
## 4              409 GEOHealth_MiPeru_Chavinillo      32.70588      39.94412
## 5              409 GEOHealth_MiPeru_Chavinillo      32.70588      39.94412
## 6              409 GEOHealth_MiPeru_Chavinillo      32.70588      39.94412
##   exposure_temp exposure_humidity                     geometry
## 1      77.64706          55.58824 POINT Z (271508.3 8689480 0)
## 2      77.64706          55.58824 POINT Z (271508.3 8689480 0)
## 3      77.64706          55.58824 POINT Z (271626.9 8689420 0)
## 4      77.64706          55.58824 POINT Z (271626.9 8689420 0)
## 5      77.64706          55.58824 POINT Z (271626.9 8689420 0)
## 6      77.64706          55.58824 POINT Z (271626.9 8689420 0)
\end{verbatim}

\begin{verbatim}
## Deleting source `/Users/gabriellebenoit/Documents/GitHub/peru_air/spatial_data_final.gpkg' using driver `GPKG'
## Writing layer `spatial_data_final' to data source 
##   `/Users/gabriellebenoit/Documents/GitHub/peru_air/spatial_data_final.gpkg' using driver `GPKG'
## Writing 1989 features with 31 fields and geometry type 3D Point.
\end{verbatim}

\subsection{Explore which sensors were used, how many participants were
assigned to
it}\label{explore-which-sensors-were-used-how-many-participants-were-assigned-to-it}

Expected and fine --- the nearest-feature algorithm is working
correctly. A few things to note: - 180119 and 159005 cover the bulk of
participants (750 and 612) --- results will be heavily influenced by
these two sensors - 159435 and 180021 have very few participants
assigned (24 and 13) --- these are likely on the geographic periphery of
the study area - The 5 unused sensors are simply outside the range of
participant locations

Limitations: exposure assignment was constrained to 6 of 11 sensors,
with the majority of participants assigned to just 2 sensors --- which
reduces spatial variability in exposure estimates.

\section{Load Data}\label{load-data}

\begin{verbatim}
##   nearest_sensor_id          nearest_sensor_name   n
## 1            180119  GEOHealth_PuenteP_Estadio_1 750
## 2            159005  GEOHealth_MiPeru_Chavinillo 612
## 3            180043        GEOHealth_SanMa_IE005 471
## 4            159599   GeoHealth_Comas_2055PAbril 119
## 5            159435 GEOHealth_Ventanilla_NSBelen  24
## 6            180021 GEOHealth_Carab_VictorRaulHT  13
\end{verbatim}

\begin{center}\includegraphics{PurpleAir_SocioDem_files/figure-latex/unnamed-chunk-7-1} \end{center}

\subsection{Examine contextual variables --
clean}\label{examine-contextual-variables-clean}

\begin{verbatim}
##    Var1 Freq
## 1     0   97
## 2     1   31
## 3    10   54
## 4    11  549
## 5    12  101
## 6    13   77
## 7    14  149
## 8  14.5    1
## 9    15   30
## 10   16   79
## 11   17    6
## 12   18    9
## 13   19   10
## 14    2   40
## 15   20    2
## 16   23    1
## 17    3   60
## 18    4   44
## 19    5   86
## 20    6  290
## 21    7   39
## 22    8   52
## 23    9  110
## 24 <NA>   72
\end{verbatim}

\begin{verbatim}
##                      
##                          0    1
##   none                  57   29
##   primary              391  135
##   secondary_or_higher 1136  115
\end{verbatim}

\begin{verbatim}
##      civil_stat   n
## 1   Conviviente 645
## 2     Casado(a) 552
## 3    Soltero(a) 408
## 4   Separado(a) 141
## 5      Viudo(a) 138
## 6          <NA>  73
## 7 Divorciado(a)  32
\end{verbatim}

\begin{verbatim}
##          occupation   n
## 1    Amo(a) de casa 634
## 2  Auto-empleado(a) 446
## 3 Sin empleo actual 327
## 4       Empleado(a) 297
## 5       Jubilado(a) 114
## 6         Freelance  94
## 7              <NA>  75
## 8        Estudiante   2
\end{verbatim}

\begin{verbatim}
## 
##         partnered            single separated_widowed              <NA> 
##              1197               408               311                73
\end{verbatim}

\begin{verbatim}
## 
##     employed    homemaker not_employed         <NA> 
##          837          634          443           75
\end{verbatim}

\begin{verbatim}
## 
## --- education_cat ---
##                      
##                          0    1
##   none                  57   29
##   primary              387  135
##   secondary_or_higher 1134  112
## 
## --- civil_stat_cat ---
##                    
##                       0   1
##   partnered         979 182
##   single            334  58
##   separated_widowed 265  36
## 
## --- occupation_cat ---
##               
##                  0   1
##   employed     715 101
##   homemaker    482 124
##   not_employed 381  51
## 
## --- htn ---
##                      
##                          0    1
##   HTA diastólica        87   19
##   HTA sistodiastólica  185   33
##   HTA sistólica        154   10
##   Sin hipertensión    1152  214
## 
## --- native_lang ---
##                   
##                       0    1
##   Castellano       1306  176
##   Quechua o aimara  272  100
## 
## --- health_ins ---
##                                 
##                                    0   1
##   Entidad prestadora de salud     11   1
##   Essalud                        349  32
##   Fuerzas armadas o policiales    46   0
##   No está afiliado               217  45
##   No sabe                         35  22
##   Seguro integral de salud (SIS) 888 175
##   Seguro privado de salud         32   1
## 
## --- chronic_dis ---
##     
##        0   1
##   No 982 190
##   Sí 596  86
## 
## --- sex ---
##            
##                0    1
##   Femenino  1067  242
##   Masculino  511   34
\end{verbatim}

\begin{verbatim}
##            
##               0   1
##   SIS       890 178
##   Essalud   350  32
##   uninsured 220  45
##   other     124  24
\end{verbatim}

\begin{verbatim}
##                      
##                          0    1
##   HTA diastólica        87   19
##   HTA sistodiastólica  185   33
##   HTA sistólica        154   10
##   Sin hipertensión    1152  214
\end{verbatim}

\begin{verbatim}
##               
##                   0    1
##   none         1154  217
##   hypertension  429   62
\end{verbatim}

\begin{verbatim}
## [1] "numeric"
\end{verbatim}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
##   15.82   25.51   28.32   28.85   31.42   51.85      78
\end{verbatim}

\subsection{Check missingness}\label{check-missingness}

\begin{center}\includegraphics{PurpleAir_SocioDem_files/figure-latex/unnamed-chunk-9-1} \end{center}

\begin{verbatim}
## 
##    0    1 
## 1584  279
\end{verbatim}

\begin{verbatim}
## [1] 1854
\end{verbatim}

\begin{verbatim}
##   exposure_pm25   n
## 1      30.93462  24
## 2      32.60750 471
## 3      32.70588 612
## 4      33.97500 750
## 5      39.63182  13
## 6      40.08182 119
\end{verbatim}

\subsection{Create standardized versions of PM 2.5, PM 10, temperature,
and
humidity}\label{create-standardized-versions-of-pm-2.5-pm-10-temperature-and-humidity}

\# and quartile for PM 2.5

\# Interpretation: SD models: OR = dementia odds per 1 SD increase in
exposure Quartile models: OR = dementia odds relative to lowest exposure
group

\begin{verbatim}
## [1] "numeric"
\end{verbatim}

\subsection{Descriptive Exploration}\label{descriptive-exploration}

\begin{verbatim}
## # A tibble: 3 x 6
##   dc_binary     n pm25_mean pm25_sd pm10_mean pm10_sd
##       <dbl> <int>     <dbl>   <dbl>     <dbl>   <dbl>
## 1         0  1584      33.6    1.85      39.7    2.30
## 2         1   279      33.6    1.78      39.6    2.22
## 3        NA   126      33.6    1.84      39.8    2.29
\end{verbatim}

\# boxplots \# pm 2.5

\begin{center}\includegraphics{PurpleAir_SocioDem_files/figure-latex/unnamed-chunk-12-1} \end{center}

\section{pm 10}\label{pm-10}

\begin{center}\includegraphics{PurpleAir_SocioDem_files/figure-latex/unnamed-chunk-13-1} \end{center}

\subsection{Analysis (Thursday, April
9)}\label{analysis-thursday-april-9}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  dc\_binary or any\_relevant\_dem as primary outcome
\item
  stratified analyses for older and younger adults with their continuous
  scores as secondary outcome
\end{enumerate}

\# determine how many NAs there are for any\_relevant dementia,
dc\_binary, rudas, ace, pfaq \# how do they or do they not overlap?

\begin{verbatim}
## na_per_row
##    0    1    2    3    5 
## 1059  756   48   54   72
\end{verbatim}

\begin{verbatim}
## any_relevant_dem        dc_binary            rudas        ace_score 
##              126              126               72              624 
##             pfaq         geometry 
##              426                0
\end{verbatim}

\begin{center}\includegraphics{PurpleAir_SocioDem_files/figure-latex/unnamed-chunk-14-1} \end{center}

\subsection{Delete observations that are missing all five variables
because they need at least one of those measures to be able to be in our
analyses
meaningfully.}\label{delete-observations-that-are-missing-all-five-variables-because-they-need-at-least-one-of-those-measures-to-be-able-to-be-in-our-analyses-meaningfully.}

\begin{verbatim}
## [1] 1917
\end{verbatim}

\begin{verbatim}
##   n_rudas n_ace n_pfaq n_dc
## 1    1917  1365   1563 1863
\end{verbatim}

\begin{verbatim}
## # A tibble: 2 x 4
##   took_rudas took_ace mean_age     n
##   <lgl>      <lgl>       <dbl> <int>
## 1 TRUE       FALSE        69.1   552
## 2 TRUE       TRUE         43.2  1365
\end{verbatim}

\begin{verbatim}
## # A tibble: 2 x 5
##   took_ace min_age max_age mean_age     n
##   <lgl>      <dbl>   <dbl>    <dbl> <int>
## 1 FALSE         60      95     69.1   552
## 2 TRUE          30      59     43.2  1365
\end{verbatim}

\subsection{Primary analysis: full
sample}\label{primary-analysis-full-sample}

\begin{verbatim}
## dc_binary ~ exposure + age + sex
\end{verbatim}

\subsection{Secondary analysis: older adults
(60+)}\label{secondary-analysis-older-adults-60}

\begin{verbatim}
## as.numeric(rudas) ~ exposure + age + sex
\end{verbatim}

\subsection{Secondary analysis: younger adults
(30-59):}\label{secondary-analysis-younger-adults-30-59}

\begin{verbatim}
## as.numeric(ace_score) ~ exposure + age + sex
\end{verbatim}

\subsection{Create the age groups:}\label{create-the-age-groups}

\subsection{Prep}\label{prep}

\subsection{Model 1}\label{model-1}

Full sample, binary outcome

\subsection{Model 2}\label{model-2}

Older adults (60+), RUDAS

\subsection{Model 3}\label{model-3}

Younger adults (30-59), ACE

\subsection{Combine}\label{combine}

All results - binary results are ORs - linear results are beta
coefficients - they are in separate facets so the scales don't mix

\begin{center}\includegraphics{PurpleAir_SocioDem_files/figure-latex/unnamed-chunk-25-1} \end{center}

\begin{verbatim}
## # A tibble: 4 x 5
##   exposure    estimate conf.low conf.high p.value
##   <chr>          <dbl>    <dbl>     <dbl>   <dbl>
## 1 PM2.5          0.456   -0.423     1.33    0.309
## 2 PM10           0.477   -0.399     1.35    0.285
## 3 Temperature   -0.148   -1.07      0.776   0.753
## 4 Humidity      -0.402   -1.34      0.531   0.397
\end{verbatim}

\subsection{Sensor zone comparison table to show descriptively whether
zones with higher PM2.5 tend to have worse cognitive
scores}\label{sensor-zone-comparison-table-to-show-descriptively-whether-zones-with-higher-pm2.5-tend-to-have-worse-cognitive-scores}

\# No dose-response pattern for PM2.5 → cognitive decline. Looking at
the four sensors with adequate sample size (ignore Ventanilla n=22 and
Carab n=13 --- too small to trust): The highest PM2.5 zone (Comas) has
the lowest \% DC and highest RUDAS scores. This is your ecological
confounding artifact made visible --- Comas residents are younger, more
educated, or otherwise healthier despite higher pollution. The sensor
zones are not exchangeable populations.

This table is a valuable finding to present --- it demonstrates why
naive ecological exposure assignment produces misleading results, and
motivates future work with better exposure characterization; a
methodological lesson rather than a failed analysis.

\begin{verbatim}
## # A tibble: 6 x 6
##   nearest_sensor_name           pm25 pct_dc mean_rudas mean_ace     n
##   <chr>                        <dbl>  <dbl>      <dbl>    <dbl> <int>
## 1 GEOHealth_Ventanilla_NSBelen  30.9   14.3       3.45     77.9    22
## 2 GEOHealth_SanMa_IE005         32.6   16.6       6.80     78.1   456
## 3 GEOHealth_MiPeru_Chavinillo   32.7   15.1       6.85     77.6   587
## 4 GEOHealth_PuenteP_Estadio_1   34.0   14.1       7.84     79.0   725
## 5 GEOHealth_Carab_VictorRaulHT  39.6   15.4       5.38     78.4    13
## 6 GeoHealth_Comas_2055PAbril    40.1   13.5      10.4      78.0   114
\end{verbatim}

\subsection{Highways}\label{highways}

The study area runs along what looks like a major highway corridor (the
blue trunk road running north-south). Our participant points are
clustered along and near this road. The red/pink dementia cases don't
obviously cluster in one spot, but proximity to that trunk road varies
meaningfully across participants --- unlike the PM2.5 values which
barely vary at all.

\begin{verbatim}
## Reading layer `highways_export' from data source 
##   `/Users/gabriellebenoit/Documents/GitHub/peru_air/highways_export.gpkg' 
##   using driver `GPKG'
## Simple feature collection with 345 features and 24 fields
## Geometry type: LINESTRING
## Dimension:     XY
## Bounding box:  xmin: 264542.2 ymin: 8681310 xmax: 277584.6 ymax: 8692089
## Projected CRS: WGS 84 / UTM zone 18S
\end{verbatim}

\begin{verbatim}
##  [1] "osm_id"          "name"            "alt_name"        "bridge"         
##  [5] "destination"     "destination.ref" "foot"            "highway"        
##  [9] "junction"        "lane_markings"   "lanes"           "layer"          
## [13] "maxheight"       "maxspeed"        "motorroad"       "noname"         
## [17] "note"            "old_name"        "oneway"          "placement"      
## [21] "ref"             "source"          "surface"         "turn.lanes"     
## [25] "geom"
\end{verbatim}

\begin{verbatim}
## < table of extent 0 >
\end{verbatim}

\begin{verbatim}
## [1] 345
\end{verbatim}

\begin{verbatim}
## 
##   primary secondary     trunk 
##        22       240        83
\end{verbatim}

\begin{verbatim}
##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
##    9.293  331.501  754.896 1240.405 2053.607 4612.723
\end{verbatim}

Meaningful continuous variation from 9 meters to 4.6 km. - Median 755m
--- half of the participants live within \textasciitilde750m of a major
road - Some very close (9m) --- essentially on the road - Max 4.6km ---
good spread at the far end - Right-skewed (mean 1,240m
\textgreater\textgreater{} median 755m) --- confirms the need to
log-transform

\begin{verbatim}
## # A tibble: 4 x 7
##   term          estimate std.error statistic  p.value conf.low conf.high
##   <chr>            <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
## 1 (Intercept)      0.239   0.439       -3.26 1.11e- 3   0.0999     0.560
## 2 log_dist_road    1.07    0.0523       1.29 1.95e- 1   0.967      1.19 
## 3 age_n            0.990   0.00491     -2.04 4.11e- 2   0.980      1.00 
## 4 sexMasculino     0.305   0.192       -6.19 6.17e-10   0.206      0.438
\end{verbatim}

\begin{verbatim}
## # A tibble: 4 x 7
##   term          estimate std.error statistic p.value conf.low conf.high
##   <chr>            <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>
## 1 (Intercept)    8.71       5.50     1.58      0.114   -2.09     19.5  
## 2 log_dist_road -0.112      0.368   -0.304     0.762   -0.835     0.611
## 3 age_n         -0.0101     0.0699  -0.144     0.885   -0.147     0.127
## 4 sexMasculino  -0.00838    0.975   -0.00859   0.993   -1.92      1.91
\end{verbatim}

\begin{verbatim}
## # A tibble: 4 x 7
##   term          estimate std.error statistic   p.value conf.low conf.high
##   <chr>            <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>
## 1 (Intercept)     92.5      2.30       40.2  1.28e-233   88.0      97.0  
## 2 log_dist_road   -0.562    0.235      -2.40 1.67e-  2   -1.02     -0.102
## 3 age_n           -0.269    0.0358     -7.51 1.03e- 13   -0.339    -0.199
## 4 sexMasculino     4.69     0.720       6.51 1.02e- 10    3.28      6.10
\end{verbatim}

\begin{verbatim}
## # A tibble: 2 x 5
##   near_road_500m pct_dc mean_rudas mean_ace     n
##   <lgl>           <dbl>      <dbl>    <dbl> <int>
## 1 FALSE            16.2       7.13     77.8  1250
## 2 TRUE             12.7       7.84     79.2   667
\end{verbatim}

This is the most interesting result yet. Participants within 500m of a
major road have lower rates of cognitive decline (12.7\% vs 16.2\%) and
higher cognitive scores (RUDAS 7.84 vs 7.13, ACE 79.2 vs 77.8) --- the
opposite of what you'd expect if road proximity is harmful. This is the
same ecological confounding pattern observed with PM2.5 --- the Comas
sensor (highest PM2.5) also had the best cognitive scores. It's telling
a consistent story: participants living closer to major roads in this
study area are systematically different in ways that protect cognition
--- likely younger, more educated, better access to healthcare, higher
SES. Urban proximity in a peri-urban Lima context may mean better
services, not worse health.

\subsection{Regression Models adjusted for age and
sex}\label{regression-models-adjusted-for-age-and-sex}

\begin{verbatim}
## # A tibble: 1 x 5
##   term          estimate conf.low conf.high p.value
##   <chr>            <dbl>    <dbl>     <dbl>   <dbl>
## 1 log_dist_road     1.07    0.967      1.19   0.195
\end{verbatim}

\begin{verbatim}
## # A tibble: 1 x 5
##   term          estimate conf.low conf.high p.value
##   <chr>            <dbl>    <dbl>     <dbl>   <dbl>
## 1 log_dist_road   -0.112   -0.835     0.611   0.762
\end{verbatim}

\begin{verbatim}
## # A tibble: 1 x 5
##   term          estimate conf.low conf.high p.value
##   <chr>            <dbl>    <dbl>     <dbl>   <dbl>
## 1 log_dist_road   -0.562    -1.02    -0.102  0.0167
\end{verbatim}

\subsection{Figure}\label{figure}

\begin{verbatim}
## # A tibble: 4 x 5
##   buffer_zone pct_dc mean_rudas mean_ace     n
##   <fct>        <dbl>      <dbl>    <dbl> <int>
## 1 Within 100m   12.2       7.35     80.8   159
## 2 100–500m      12.9       7.99     78.6   508
## 3 500m–1km      16.0       8.01     77.7   506
## 4 Beyond 1km    16.3       6.53     77.9   744
\end{verbatim}

\begin{center}\includegraphics{PurpleAir_SocioDem_files/figure-latex/unnamed-chunk-30-1} \end{center}

The only significant finding is ACE in younger adults. Binary and RUDAS
are null. This is actually a coherent and interpretable pattern: Why
only younger adults?

ACE is a more sensitive, higher-ceiling instrument than RUDAS. Younger
adults (mean age 43) have more cognitive reserve and more variance in
scores to detect --- so subtle environmental effects show up there
first. Older adults' RUDAS scores may already reflect age-related
decline that swamps any road proximity effect.

What the ACE finding means: Among 30--59 year olds, each unit increase
in log-distance from a major road is associated with a 0.56 point
decrease in ACE score. Given ACE is scored out of 100, that's modest but
statistically real. The direction --- farther from roads = worse
cognition --- points to urban access rather than pollution as the
operative mechanism in this setting.

\subsection{\texorpdfstring{The \emph{storyline} for the
chapter:}{The storyline for the chapter:}}\label{the-storyline-for-the-chapter}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  PM2.5 sensor zones --- null, insufficient spatial variability
\item
  Distance to road --- significant for ACE in younger adults,
  counterintuitive direction
\item
  Interpretation --- urbanization-health paradox in peri-urban Lima,
  road proximity as access proxy
\end{enumerate}

Implication --- future studies need personal exposure monitors + SES
adjustment to disentangle pollution from access

\end{document}
